runtime: python
env : flex
entrypoint: gunicorn -b :$PORT -k flask_sockets.worker application:app

runtime_config:
  python_version : 3

manual_scaling :
  instances : 8
resources :
  cpu: 3
  memory_gp : 16
  disk_size_gb : 100